version: "2"
volumes:
    mongo-data:
services:
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "admin"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "${MONGO_PORT}:27017"
  api:
    restart: always
    image: scpomedialab/ouatterrir-api
    build: .
    links:
     - "mongo"
    environment:
      MONGO_DB: "ouatterrir"
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: "admin"
      MONGO_PASSWORD: "password"
      API_PORT: 3000
    ports:
      - "${API_PORT}:3000"
  client:
    restart: always
    image: scpomedialab/ouatterrir-client
    build: ./client
    links:
     - "api"
    environment:
      API_HOST: api
      API_PORT: 3000
    ports:
      - "${PUBLIC_PORT}:80"
