version: "2"
volumes:
    mongo-data:
services:
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "admin"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "27117:27017"
  backend:
    restart: always
    image: scpomedialab/ouatterrir-backend
    build: .
    links:
     - "mongo:mongo"
    environment:
      MONGO_DB: "ouatterrir"
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: "admin"
      MONGO_PASSWORD: "password"
      API_PORT: 5000
    ports:
      - "3000:3000"
