apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ouatterrir

namePrefix: ouatterrir-

bases:
  - ../../base/

resources:
  - ingress.yml

commonLabels:
  stage: development

secretGenerator:
- name: mongodb
  literals:
    - database=ouatterrir
    - root_password=password
    - root_username=admin

images:
  - name: scpomedialab/ouatterrir-client
    newTag: 'master'
  - name: scpomedialab/ouatterrir-api
    newTag: 'master'
  - name: mongo
    newTag: '4.2'
