apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toflit18

namePrefix: toflit18-

bases:
  - ../../base/

resources:
  - ingress.yml

commonLabels:
  stage: staging

secretGenerator:
- name: mongodb
  env: mongodb.env

images:
  - name: scpomedialab/ouatterrir-client
    newTag: '1.4'
  - name: scpomedialab/ouatterrir-api
    newTag: '1.4'
  - name: mongo
    newTag: '4.2'
